### ISSUE TITLE
a way to re-define in boards.txt SBC pins  

### ISSUE THREAD

**Issue by blairq** [gloomyandy/RepRapFirmware#53]
can be added options to redefine APIN_SBC_SPI_MOSI ,APIN_SBC_SPI_MISO  and so ? 

to be able to use other pins than the ones on exp2

**Comment by gloomyandy** [comment]
Firstly those defines "APIN_SBC_SPI_MOSI" etc are for the Duet boards and are not used by either the LPC or STM ports. Secondly the connections used for the SBC SPI connections are pretty much fixed by a combination of the mcu and the board layout. They must be connected to a hardware SPI unit (that is not already in use for other purposes) and they must go to easily accessible pins on the board. I'm not sure that these constraints really leave any alternatives for any of the supported boards.
